ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
        host = ${?HOST}
    }
    application {
        modules = [ com.aos.chatbot.ApplicationKt.module ]
    }
}

app {
    mode = "full"
    mode = ${?MODE}
    database {
        path = "./data/aos.db"
        path = ${?DATABASE_PATH}
    }
    data {
        path = "./data"
        path = ${?DATA_PATH}
    }
}
